### ISSUE TITLE
Не работает OTA обновление

### ISSUE THREAD

**Issue by sven4eg** [karevn/android_device_xiaomi_markw-RR#12]
Los 6.10 не работает OTA обновление. Доступно обновление 7.10 которое я проигнорировал. При проверке обновления : The update check failed.
Последняя успешная проверка 19.10

Из logcat:

10-23 22:46:03.193 D/UpdatesActivity( 5154): Checking http://lineage.karevn.com//v1/markw/unofficial/51ee5f26fe
10-23 22:46:03.483 D/DownloadClient( 5154): Downloading
10-23 22:46:03.486 E/DownloadClient( 5154): The server replied with code 404
10-23 22:46:03.488 E/UpdatesActivity( 5154): Could not download updates list

**Comment by karevn** [comment]
Не надо было игнорировать.

**Comment by sven4eg** [comment]
Прошил 20.10 без вайпов. В ота показывает доступной к скачиванию... 20.10 
Тоже не игнорировать?
