### ISSUE TITLE
Не настроенный сканер отпечатков реагирует на ЛЮБЫЕ касания

### ISSUE THREAD

**Issue by userneu** [karevn/android_device_xiaomi_markw-RR#2]
Тем самым полудня пробуждая телефон. Сканер FPC. На mokee 6 от Разиэля тоже самое и существует компромиссное решение в виде полного отключения работы сканера, посредством удаления файлов system /lib/hw/fingenprint.msm8953.so и lib64/hw/fingerprint.*.so
Меня лично оно устраивает. Но на вашей сборке я их не нашел. В общем, в идеале конечно хотелось чтобы сканер не реагировал, но хотя бы можно его вообще отрубить? Проблема распространенная на многих сборках, судя по отзывам. Спасибо.

**Comment by karevn** [comment]
У меня другой сканер, воспроизвести проблему не смогу.
Чтобы дать мне инфу для размышлений, подключитесь к телефону через `adb logcat`, погасите экран, коснитесь сканера.  То, что попадёт в логи logcat, выложите сюда.

**Comment by userneu** [comment]
Меня бы устроило банальное отключение этого сканера, я им не пользуюсь. Логи вот
[logcat.txt](https://github.com/karevn/android_device_xiaomi_markw-RR/files/1359212/logcat.txt)

**Comment by karevn** [comment]
Попробуйте решение, описанное здесь: http://en.miui.com/thread-366810-1-1.html
Проверьте, будет ли при этом работать разблокировка при наличии отпечатков. Если всё получится - внесу в общее дерево устройств.

**Comment by userneu** [comment]
Я может что-то делаю не так, но выдает следующее:
`1|markw:/ $ echo 1 > /sys/devices/soc/soc\:fpc_fpc1020/enable_wakeup`
`/system/bin/sh: can't create /sys/devices/soc/soc:fpc_fpc1020/enable_wakeup: No
such file or directory`

**Comment by karevn** [comment]
Имя файла может слегка отличаться, но в нём точно будет fpc1020

**Comment by userneu** [comment]
Следующая команда принимается вроде оболочкой
`echo 1 > /sys/devices/soc/soc\:fpc1020/wakeup_enable`
Т.е. нет ошибок. 
Но поведение сканер не изменилось. Я не пойму в чем суть того решения, там нет толкового описания.

**Comment by karevn** [comment]
Так надо туда нолик записать :)

**Comment by karevn** [comment]
Суть решения в том, что оно отключит пробуждение по сканеру. Вопрос только - совсем отключит или только когда распечаток не распознан.

**Comment by userneu** [comment]
Так, записал нолик. Но все равно - ноль эффекта. А есть идеи как отключить сканер вовсе? Все таки

**Comment by karevn** [comment]
Собсно, так он и должен отключаться. А запись точно нормально прошла?

**Comment by userneu** [comment]
Как мне проверить? Текстовый редактор не хочет открывать этот файл. Рут есть.

**Comment by karevn** [comment]
`cat /sys/devices/soc/soc\:fpc1020/wakeup_enable`

**Comment by userneu** [comment]
`sush: cat: /sys/devices/soc/soc:fpc1020/wakeup_enable: I/O error`

**Comment by userneu** [comment]
В комментариях http://en.miui.com/thread-366810-1-1.html некоторые пишут что не работает этот способ, может так и есть %)

**Comment by userneu** [comment]
В общем переименовал файлы fingerprint.fpc.so и сканер больше не работает. Пойдет
