### ISSUE TITLE
some issue

### ISSUE THREAD

**Issue by lovekobeme** [karevn/android_device_xiaomi_markw-RR#9]
voodoo kernel solve noise in Los(0904) version,but in other new build Los,voodoo kernel is void to noise problem.
if you touch setting→buttons→menu button→long press action→single hand mode(left) →and you long pressmenu→system immediately soft reboot.
sometimes tap setting,the Transition screen is stagnant,show a blank.

**Comment by lovekobeme** [comment]
i haven't used v4a

**Comment by karevn** [comment]
Does this issue still exist with the stock kernel?

**Comment by lovekobeme** [comment]
yes,it's exist.I've been using 10.06 Los version all the time

**Comment by lovekobeme** [comment]
1006 version until now logcat

**Comment by lovekobeme** [comment]
http://tjhdwt.com/test/1006 version logcat.txt
http://tjhdwt.com/test/1020 version logcat.txt

**Comment by lovekobeme** [comment]
http://tjhdwt.com/test/1006versionlogcat.txt
http://tjhdwt.com/test/1020versionlogcat.txt

**Comment by lovekobeme** [comment]
http://tjhdwt.com/test/1006logcat.txt
http://tjhdwt.com/test/1020logcat.txt

**Comment by karevn** [comment]
Please post gists.

**Comment by karevn** [comment]
OK, no acceptable feedback.
